### ISSUE TITLE
Users: New users cannot be created

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1004]
New users cannot be created manually or automatically.

Tried to deconstruct many different ways with no success.

**Comment by jimafisk** [comment]
Vague error message: 

![error](https://user-images.githubusercontent.com/5913244/70470718-a9d74f80-1a99-11ea-964b-1ec5112c3a2d.png)

**Comment by reillyzlab** [comment]
Closing because working since Friday morning.

**Comment by reillyzlab** [comment]
Re-opening because had another issue with user: 40001960 (created 17 hours ago)

**Comment by jimafisk** [comment]
Debugging info:
1. `vendor/symfony/validator/Constraints/Choice.php`
2. `docroot/core/lib/Drupal/Core/Validation/Plugin/Validation/Constraint/AllowedValuesConstraint.php`
3. `docroot/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/EntityReferenceItem.php`

**Comment by jimafisk** [comment]
I was worried that the langcode being set to "und" instead of "en" was potentially giving us problems given the violations I was seeing when debugging.

<details>
<summary>Debugging screenshot</summary>

![langcode](https://user-images.githubusercontent.com/5913244/70739792-a6d09f00-1ce5-11ea-91a7-f95e6c38640f.png)

</details>

I tried to correct this with some preprocess in `docroot/themes/custom/bos_admin/bos_admin.theme`:

```php
/**
 * Implements hook_form_FORM_ID_alter().
 */
function bos_admin_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $vals = $form_state->getStorage();
  $vals['entity_default_langcode'] = 'en';
  $vals['langcode'] = 'en';
  $form_state->setStorage($vals);
}
```
But still saw the same issue thrown when trying to save the form.

**Comment by reillyzlab** [comment]
Jim created a workaround using Drush - @duffy-james can you verify whether that's working with folks who were having issues on Monday.

@mmcgowanBOS @jfalvey this still needs to be resolved in general/overall. Open ticket with Acquia since 12/19.

**Comment by jimafisk** [comment]
`drush user:create yourusername --password="SetAStrongPWHashHere" --mail="youremail@example.com"`. Then in the admin UI, just make sure to enable SAML.
