### ISSUE TITLE
Department icons not centered

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1015]
Many of the department icons are not centered aligned in the sidebar circle on department pages. Select examples:
- https://www.boston.gov/departments/archaeology
   - [Icon](https://assets.boston.gov/icons/dept_icons/archaeology_icon.svg)
- https://www.boston.gov/departments/archives-and-records-management
   - [Icon](https://assets.boston.gov/icons/dept_icons/archives_and_records_icon.svg)
- https://www.boston.gov/departments/boston-centers-youth-families
   - [Icon](https://assets.boston.gov/icons/dept_icons/boston_centers_for_youth_and_families_logo.svg)
- https://www.boston.gov/departments/immigrant-advancement
   - [Icon](https://assets.boston.gov/icons/dept_icons/immigrant_advancement_logo.svg)
- https://www.boston.gov/departments/intergovernmental-relations
   - [Icon](https://assets.boston.gov/icons/dept_icons/intergovernmental_relations_logo.svg)

**Comment by phillipbentonkelly** [comment]
Issue is that those icons are not the same aspect ratio/sizes as the others. I implemented a CSS fix that makes the existing icons and the ones in these pages line up as close to the center as possible, I talked to Caroline and we made `matching aspect ratios` a requirement for new icons. This fix should be enough unless you'd want these icons edited to fix their dimensions. 

Staging: https://d8-stg.boston.gov/departments/immigrant-advancement

*TODO: Pages like this overlap with the icons due because some words are too long to be broken into the next line. If we want to try and address this it, it should be in another ticket. Ps. The best we can try to do is to see if can change the font-size on those title elements.

**Comment by andrebtlima** [comment]
@phillipbentonkelly  I'm just looking at Immigrant Advancement's icon as the example here right? Looking at other department profile pages, looks like the icons are still wonky. I'll add the other ticket about words in the header being too long to break into the next line.

**Comment by phillipbentonkelly** [comment]
Going to meet with @carolinestj to figure what the aspect ratios should be, I updated the description of this issue to include the URL of the icon being used.
