### ISSUE TITLE
Long emails in sidebar run off page (and should break to fit on page)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1058]
Long emails in sidebar run off page (and should break to fit on page)

Example:
https://www.boston.gov/departments/neighborhood-development

D8:
![Screen Shot 2019-12-09 at 1 37 14 PM](https://user-images.githubusercontent.com/20731897/70462914-de430f80-1a89-11ea-8c0f-10355376ba26.png)

D7:
![Screen Shot 2019-12-09 at 1 41 08 PM](https://user-images.githubusercontent.com/20731897/70462919-e0a56980-1a89-11ea-868b-db33eb768155.png)

**Comment by reillyzlab** [comment]
Another example: 

![Screen Shot 2019-12-09 at 4 55 04 PM](https://user-images.githubusercontent.com/20731897/70476512-d6dd2f80-1aa4-11ea-80d2-d1bf0f8a4fe0.png)

**Comment by jimafisk** [comment]
The issue is there is an extra `<div>` wrapping the field. This is happening because `{% if display_item_tag %}` returns `true` in `docroot/modules/custom/bos_vocab/modules/vocab_contact/templates/field--field-email.html.twig` which then gets a default value set `<{{ field_item_tag|default('div') }}{{ item.attributes.addClass('field__item') }}>`:

<details>
<summary>See screenshot</summary>

![extra_div](https://user-images.githubusercontent.com/5913244/70933053-2a9dca80-2009-11ea-807e-71ef12af7ebd.png)

</details>

Removing that extra markup fixes the wrap:

<details>
<summary>See screenshot</summary>

![working_wrap](https://user-images.githubusercontent.com/5913244/70933088-41442180-2009-11ea-8099-df1e1ab9f13d.png)


</details>

**Comment by reillyzlab** [comment]
REsolved so closing
