### ISSUE TITLE
Salesforce feed not coming through on Metrolist

### ISSUE THREAD

**Issue by SusannaRH22** [CityOfBoston/boston.gov-d8#1098]
Hi guys,

We haven't had many lottery opportunities lately, so been hard to see if there were Drupal 8 related issues, but we have one that should be live now and it is not, so I'm thinking there may be an issue! 
https://boston-dnd.my.salesforce.com/a1i0y000003oYwF
This is for Longwood Row. Looks like all the filter logic should check out, but it's just not showing up on the site.

Also, the neighborhood/city fields are not showing up on listings either. This was reported but I wasn't sure if it was a Drupal 8 migration bug or not, because I was reviewing the code logic and couldn't figure how the salesforce fields were actually being referenced. For now, I've asked Caitlin to include the Neighborhood/City in the listing title, as an easy fix, but I do think the listing is supposed to include the neighborhood field, and maybe also the secondary "outside boston location" field-- would be good to know the expected behavior here, and if it is buggin currently.

![Metrolist listing fields](https://user-images.githubusercontent.com/23034098/70925140-bb1fdf00-1ff8-11ea-8b88-7b650ceedb7e.PNG)

**Comment by jimafisk** [comment]
Potentially related:

> Acquia recently became aware of an issue with the latest release of the Acquia Connector module for Drupal 8 applications, 8.x-1.17.
>
> Some applications that have been updated to use the latest version of this module have reported issues with cron tasks failing.

**Comment by jimafisk** [comment]
I've worked out the issue, basically the feed was broken because Drupal asserts a very strict Uri scheme where external links need to start with `HTTPS`, however many of the records coming from Salesforce simple start with `WWW` or the domain name and assume an http protocol. That's why we see so many errors that look like this in our logs:

> [error]  InvalidArgumentException: The URI 'www.boston.gov/sites/default/files/imce-uploads/2018-07/bfhc_approved_compliance_1_-_community_stabilization_project_phase_ii_1.pdf' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 282 of /app/docroot/core/lib/Drupal/Core/Url.php).

To test I removed the lottery url mapping, which allows us to import new records, including "Longwood" per the example (this record was completely missing previously):

<details>
<summary>See screenshot</summary>

![longwood](https://user-images.githubusercontent.com/5913244/71424283-22bfd500-265e-11ea-9e16-79a6fd913db8.png)

</details>

The quickest path to getting this fixed is to replace the link field with a text field, remap to salesforce, then update the view. We may want to re-implement the link field in the future so for the Drupal devs, I setup the scaffolding for an event subscriber to fix this in `docroot/modules/custom/bos_content/modules/node_metrolist/src/EventSubscriber/SalesforceEventsSubscriber.php` (this replaces [hook_salesforce_pull_entity_value_alter()](https://www.drupal.org/project/salesforce/issues/2061623#comment-11822497) from the D7 world):

<details>
<summary>See screenshot</summary>

![event_subscriber](https://user-images.githubusercontent.com/5913244/71424285-27848900-265e-11ea-9951-3d319bab2564.png)

</details>

The challenge is just getting your debugger to work with drush so you can view the code when running `lando drush salesforce_pull:pull-query`

**Comment by jimafisk** [comment]
I upgraded the salesforce module to the dev version and applied [a patch](https://www.drupal.org/project/salesforce/issues/3045542#comment-13134578) which fixed the salesforce pull issues:

<details>
<summary>See screenshot</summary>

![queue_run](https://user-images.githubusercontent.com/5913244/71427204-c7084280-2683-11ea-93ef-95264d4c058f.png)

</details>

I also ended up just implementing the Uri fix discussed above, so we're still using a link field on the `metrolist_affordable_housing` nodes. That should fix all the issues with data not coming across.

The second part of this issue regarding neighborhood/city info not showing up is likely because the salesforce module does not support mapping plain text fields to an existing taxonomy. In D7 I wrote a custom module for that: https://www.drupal.org/project/salesforce_term_ref. Someone will have to port that over to D8, we should probably create a separate issue for that.

**Comment by reillyzlab** [comment]
@SusannaRH22 or @AmyWipfler this should be working on production -- can you verify?

**Comment by AmyWipfler** [comment]
@reillyzlab Reviewed, does not seem to be working in Prod.

For example, Porter Street does not show Stoughton or Outside Boston as listed in SF:
![image](https://user-images.githubusercontent.com/55395593/71625836-01a83880-2bb8-11ea-8145-a0a29bd9c87b.png)

![image](https://user-images.githubusercontent.com/55395593/71625858-1ab0e980-2bb8-11ea-8b57-ddf3c9c75814.png)

**Comment by reillyzlab** [comment]
Currently 9 live that should have come down that are still displaying. 

But, more urgent: 
Currently 1 that's set live in salesforce, but not showing on boston.gov
Was set live - 12/27
156 Porter Street, East Boston
DND driving users to lotteries but no info appearing


Intermittent records have come through as live since migration. None have come down. The following records/properties have gone live in Salesforce since Drupal 8 launch and should have come through to Drupal.
![image (11)](https://user-images.githubusercontent.com/20731897/71626427-19cd8700-2bbb-11ea-8a48-0db714ee1ac2.png)
- example of one that came through: 105 Porter; example of one that didn't come through: Alder Point

After some quick sleuthing it appears as if things only marked Rental - Lottery are coming through.

**Comment by jimafisk** [comment]
I just took a quick look at this, some of the neighborhood information is coming through, for example if you go to the [second page in the lottery table](https://www.boston.gov/metrolist/lottery-and-resale?combine=&page=1) you should see:

![neighborhoods](https://user-images.githubusercontent.com/5913244/71627375-138dd980-2bc0-11ea-8b69-6e8a0699b8ab.png)

You're right that porter does not seem to be updating with neighborhood info:

![porter](https://user-images.githubusercontent.com/5913244/71627403-33bd9880-2bc0-11ea-9c6b-85dbe861c672.png)

It does look like Alder Point came through to Drupal from Salesforce:

![alder](https://user-images.githubusercontent.com/5913244/71627469-8f882180-2bc0-11ea-9528-e9aff517ff15.png)

So are the other Porter St properties:

![porter_street_props](https://user-images.githubusercontent.com/5913244/71627504-c9592800-2bc0-11ea-844e-4fb845478169.png)

So they are either not meeting our filter criteria, or not displaying because of a caching issue.

**Comment by jimafisk** [comment]
Here are the issues as I see them for why certain properties are not appearing on the [lottery page](https://www.boston.gov/metrolist/lottery-and-resale):
- **156 Porter St:** Lottery is set to "No" in Drupal
- **Alder Point:** Actually is coming across on the second page (filtering for this doesn't seem to work, but that's a separate issue):

![second_page](https://user-images.githubusercontent.com/5913244/71627773-8ac46d00-2bc2-11ea-95d1-03571b257df8.png)

**NOTE:** By far the quickest (but temporary) fix to get something like "156 Porter" to appear on the lottery page immediately is to manually [edit the record in Drupal](https://content.boston.gov/node/11555001/edit) and set the "Lottery" field to "Yes".

For a more sustainable approach, what may be happening is that if that records have not been updated in SF since we made the fixes, Drupal has no indication that it has to pull new information. We could:
1. Try to just resave the record in SF and pull again, or
2. Try the atomic approach and delete all Metrolist nodes and mapped objects and repull from scratch to get the most recent info (a guide for doing that for the Drupal devs can be found in `./scripts/local/reset_sf.sh`)

**Comment by jimafisk** [comment]
Also, regarding the outer location not showing on records like "105 Porter", those values are coming across from Salesforce:

![outer_location](https://user-images.githubusercontent.com/5913244/71627995-c27fe480-2bc3-11ea-8d25-0c7ca416ff68.png)

So there is potentially an issue with the field settings of the view: https://content.boston.gov/admin/structure/views/view/metrolist_affordable_housing

**Comment by reillyzlab** [comment]
Might have been working at one point, because Print Lofts Apartments, Turtle Pine Village, and Langley were already marked 'yes' in the 'lottery info' and were displaying on boston.gov publicly (i.e. didn't need to be manually adjusted). 

But, I did have to adjust the rest of the lottery items manually in the screenshot above (which is all records posted since launch of Drupal 8). 

All lottery records should be up-to-date on boston.gov temporarily, but we will look at a better long-term fix on Thursday.

*This is simply the fix for the records appearing/not appearing. We will resolve the rest Thursday and onward.

**Comment by AmyWipfler** [comment]
@reillyzlab Thanks for the manual short-term fix. QA'ed this and we're still missing 9 Live lotteries, and 1 more Closed lottery needs to be taken down.

**Add:**
Shawmut Estates
Parkside on Adams
Single-Family Home in Dorchester
Emery Flats
23 Ruskindale Road (Boston - Hyde Park)
Avenu at Natick
Retreat at Union Pond
Bell OImsted Park
The Schochet Companies/Symphony Plaza RHF L.P.

**Remove:**
One Homeownership Unit in South Boston, 27 H Street

Let me know if you need more details to get these manually added to ML.

Thanks!

**Comment by SusannaRH22** [comment]
Hey I've been catching up on this thread and I think that Amy is actually under the wrong impression as to what salesforce records should display according to the code logic in place. These are the logic rules you guys shared with us (Lydia) months ago:

"Content is published" AND 
"Content: Type (= Metrolist Affordable Housing)" AND
"Content: Property Address is NOT blank" AND 
"Content: Zipcode is NOT blank" AND 
"Content: Not Active is NOT True" AND 
"Content: Publish to Metrolist is True" AND 
"(Content: Lottery (= Yes) OR Content: Resale (= Yes))"

According to this criteria, attached is a spreadsheet of all records that should be showing on the Lotteries and Resales page, and a column indicating whether they are or not.

[Lotteries and Resales Page 1.2.20.xlsx](https://github.com/CityOfBoston/boston.gov-d8/files/4016655/Lotteries.and.Resales.Page.1.2.20.xlsx)

**Comment by AmyWipfler** [comment]
Made a few edits to the list above upon further investigation of the filter logic for what should be posted.

For QAing purposes, is it possible to re-send any documentation you have of the logic that Drupal leverages? The email communications I'm referencing are somewhat incomplete.

Thanks!

**Comment by AmyWipfler** [comment]
New report for all listings that should be surfaced as of 1/3/20:

![image](https://user-images.githubusercontent.com/55395593/71734686-77abda00-2e1a-11ea-865b-db2e231507b5.png)

**Comment by reillyzlab** [comment]
Think resale field was mapping accurately in Drupal. Believe we have a fix that we anticipate to be fully deployed on Monday. 

Reilly will write up documentation and regroup with @AmyWipfler on Monday.

**Comment by andrebtlima** [comment]
@AmyWipfler @SusannaRH22 the fix that Reilly was referring to above has been deployed to production and looks like things are mapping accurately now.
