### ISSUE TITLE
Look into video component functionality - conflict between live and pre-recorded video

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1106]
Look into video component functionality.

Video component has a 'youtube' channel and non youtube channel feature, but they don't appear to do anything different.

There is a rare occasion when a live video feed should appear on the video component (example: media event), but the general video component should maintain the cable stream and these happen at the same time.

We need to figure out the desired functionality of the video component and adjust/re-adjust the component accordingly.

Overarching: It serves up (or should serve up) live and pre-recorded video, but it's not intuitively obvious how.

![Screen Shot 2019-12-12 at 3 54 23 PM](https://user-images.githubusercontent.com/20731897/71020185-d60e5400-20c9-11ea-95d0-41b6cf4f3141.png)

![Screen Shot 2019-12-12 at 3 53 58 PM](https://user-images.githubusercontent.com/20731897/71020188-d9a1db00-20c9-11ea-8640-32085568b8aa.png)

Unsure if this is a bug.

**Comment by reillyzlab** [comment]
@duffy-james is this still an issue or did we resolve?

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this still an issue or can I close out this ticket?

**Comment by duffy-james** [comment]
@rachelsater we can close out. I don't know what Reilly is talking about. The "channel" option is just for when you're linking to a YouTube "channel" vs. an individual video link. We use the "channel" option for the [Boston City TV](https://www.boston.gov/departments/broadband-and-cable/watch-boston-city-tv) and [City Council TV](https://www.boston.gov/departments/city-council/watch-boston-city-council-tv) pages, since they are channel streams and not individual videos.
