### ISSUE TITLE
"Email" link not working in WYSIWYG field

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1164]
When a user clicks on the "link" button in the WYSIWYG field, located here:
![image](https://user-images.githubusercontent.com/7929556/71837319-269f1e80-3084-11ea-9b67-1eb563f722a7.png)

There's an option to add an email or phone link:
![image](https://user-images.githubusercontent.com/7929556/71837487-85fd2e80-3084-11ea-860d-e021940408a6.png)

The "phone" option is broken, which I've noted in #980. But, it looks like the email option is also broken. When I add an email, it creates a "mailto" link but ignores the @ symbol and adds "%40":
![image](https://user-images.githubusercontent.com/7929556/71837655-f60bb480-3084-11ea-91ca-cf9fd6e8fc18.png)

Here it is in the code:
![image](https://user-images.githubusercontent.com/7929556/71837715-16d40a00-3085-11ea-8e12-4e2afdaebe64.png)

I changed the code to use the @ symbol and it worked, so it's just an issue with the WYSIWYG "link" option.

**Comment by duffy-james** [comment]
This is also preventing the form from sending the message, even though it looks like the form has submitted to users. I just tested on production, and I'm unable to send a message to myself.

**Comment by andrebtlima** [comment]
@subaha-cob this isn't working for me on staging. Still getting the %40 instead of @ on both the back and front end. I know the user is meant to highlight text _and _then__ press the link button in the WSYWIG but i think this still needs to be fixed. Also tried putting my email in and sending one to myself as a test and it didn't work:
<img width="1427" alt="Screen Shot 2020-01-10 at 3 37 22 PM" src="https://user-images.githubusercontent.com/57111927/72185208-47d37800-33c0-11ea-87a3-5dc58560c5d9.png">
<img width="1425" alt="Screen Shot 2020-01-10 at 3 37 38 PM" src="https://user-images.githubusercontent.com/57111927/72185215-4b66ff00-33c0-11ea-8161-e42ada36587c.png">
