### ISSUE TITLE
GIFs buggin out in Listing Page - List

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1176]
Example here: https://content.boston.gov/news?field_contact_target_id%5B1526%5D=1526&field_published_date_value%5Bmin%5D=&field_published_date_value%5Bmax%5D=&title=&page=1

**Comment by subaha-cob** [comment]
@andrebtlima I tested this page and downloaded the gifs. I believe the problem here is with the gifs. They are not clear at all. We need new ones to replace this ones.

**Comment by andrebtlima** [comment]
OK got it.

**Comment by subaha-cob** [comment]
Let me take a second look at this then.

**Comment by subaha-cob** [comment]
@andrebtlima after much investigation, I come to find out that with Drupal adding gifs as a thumbnail will not work. They can add the gif in the body, but not as a thumbnail. They need to remove it in the thumbnail section and add a regular image instead.

But remember for older posts/articles, change the revision dates and author/published date to the original dates of the article. otherwise it will bubble as if just published.

Moving to test on UAT

**Comment by davidrkupton** [comment]
Note: "animated gifs" wont work well as thumbnails, regular gifs are OK

**Comment by andrebtlima** [comment]
@subaha-cob and @sebastianebarb I'm going to close this ticket seeing as it's more a question of practice than a "bug" per say. Feel free to push back on that. Otherwise I think, the thing to do is to change the thumbnails of the posts that have a animated gif as a thumbnail to a regular GIF for static image, and repost.
