### ISSUE TITLE
Feedback form not working in top navbar on Boston.gov

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1267]
The form to submit feedback emails at the top of the site isn't working:
![image](https://user-images.githubusercontent.com/7929556/76088837-b8dd7900-5f86-11ea-98c2-6cae46293f8a.png)
![image](https://user-images.githubusercontent.com/7929556/76088884-c72b9500-5f86-11ea-98df-c080a045d3b6.png)

This form view pops up anytime you click on a "mailto:" link on the site, but the issue is only related to the "feedback" button in the top nav bar. I tested out the "mailto:" links in other sections of the site and they appear to be working.

I talked with @davidrkupton about this issue, and he's guessing it might be web apps related. @phillipbentonkelly can you take a look?

**Comment by reillyzlab** [comment]
@phillipbentonkelly will prioritize 'fixing' this temporarily by swapping this form out for a mailto link that would open their mail client.

For a longer term solution, @andrebtlima will take this on as a mini project to determine how to best handle this.

**Comment by phillipbentonkelly** [comment]
After Dave and I looked at it turns out that this form is working, we tested by sending several request to the API and we responses after some random time delay. Also, James remembered that we changed this form to be sent to another team. He emailed that team to check if they are getting those emails and if they are responding. Closing this for now, can re-open if something else comes up.
