### ISSUE TITLE
Remove camel casing functions from fire department content on my neighborhood

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1470]
We can remove the camel casing functions from the Fire Department information on my neighborhood as the capitalization has been fixed in the source data.

**Comment by mmcgowanBOS** [comment]
OK. This has been updated and is now on Dev to review. Note, we no longer copy the full MNL content type into non-Prod environments in Acquia. This was decided due to excessive bloating of DBs ane DB backups with Acquia. Knowing this, I went ahead and manually added your test address "89 Orleans St #1 ...: into the DB content type "Neighborhood Lookup". So please search for that. 

https://d8-dev.boston.gov/my-neighborhood

Once you've tested this out. I can go ahead and move to Stg and then Prod.

**Comment by paylakatel** [comment]
This looks good - thanks for updating.
<img width="1323" alt="Screen Shot 2020-06-30 at 10 04 16 AM" src="https://user-images.githubusercontent.com/12868231/86135606-10b16a00-bab9-11ea-8a84-f9c124334067.png">

**Comment by mmcgowanBOS** [comment]
OK. This has been deployed to Prod. Closing for now.
