### ISSUE TITLE
Update note text on my neighborhood snow route card

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1471]
On the snow route card, can we update the "Note" text to read:

> During a declared snow emergency, will will ticket and tow your car if you park on a snow route. 
> 
> There may be other snow emergency arteries in your area, [check here for all snow emergency parking restrictions](https://www.boston.gov/departments/311/snow-emergency-parking).

**Comment by mmcgowanBOS** [comment]
OK. This has been updated and is now on Dev to review. Note, we no longer copy the full MNL content type into non-Prod environments in Acquia. This was decided due to excessive bloating of DBs ane DB backups with Acquia. Knowing this, I went ahead and manually added your test address "89 Orleans St #1 ...: into the DB content type "Neighborhood Lookup". So please search for that. 

https://d8-dev.boston.gov/my-neighborhood

Once you've tested this out. I can go ahead and move to Stg and then Prod.

**Comment by paylakatel** [comment]
This looks good - thanks for updating.
<img width="1324" alt="Screen Shot 2020-06-30 at 10 06 48 AM" src="https://user-images.githubusercontent.com/12868231/86135929-6b4ac600-bab9-11ea-9179-776619f4a484.png">

**Comment by mmcgowanBOS** [comment]
OK. This has been deployed to Prod. Closing for now.
