### ISSUE TITLE
Trash and Recycling information missing on address in my neighborhood that does show up in Recollect app

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1483]
The trash and recycling information isn't showing for 89 Orleans St East Boston, 02128:
<img width="819" alt="Screen Shot 2020-06-29 at 2 19 23 PM" src="https://user-images.githubusercontent.com/12868231/86041356-89f68180-ba13-11ea-8e1e-e6de408c98aa.png">

When I search for these addresses in the Recollect application, I do get collection information: 
![IMG_3404](https://user-images.githubusercontent.com/12868231/86041183-4865d680-ba13-11ea-94d8-cd5c76d05f76.png)

Could you look into why this address might be getting missed from the Recollect api? I'm worried if it is happening with this address, it could be happening with more that we just haven't run into yet. 

Thanks,
Kayla

**Comment by mmcgowanBOS** [comment]
Yes, i noticed this too and we discussed in Slack. I have come up with a fix. This was due to a switch to the new endpoint, etc.

This has been updated and is now on Dev to review. Note, we no longer copy the full MNL content type into non-Prod environments in Acquia. This was decided due to excessive bloating of DBs ane DB backups with Acquia. Knowing this, I went ahead and manually added your test address "89 Orleans St #1 ...: into the DB content type "Neighborhood Lookup". So please search for that. 

https://d8-dev.boston.gov/my-neighborhood

Once you've tested this out. I can go ahead and move to Stg and then Prod.

**Comment by paylakatel** [comment]
This looks good - thanks for updating.
<img width="1164" alt="Screen Shot 2020-06-30 at 10 07 50 AM" src="https://user-images.githubusercontent.com/12868231/86136027-903f3900-bab9-11ea-9c4f-615d170a97a1.png">

**Comment by mmcgowanBOS** [comment]
OK. This has been deployed to Prod. Closing for now.
