### ISSUE TITLE
My neighborhood: Add delay between "Loading..." message and "No address was found" message

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1526]
On my neighborhood, could we add a small delay between the "Loading..." message and the "No address was found" message when someone is searching for an address? 

I'm not sure on exactly how long the delay should be, but enough so that when someone searches for an address that _does_ exist, they don't see that error message flash. Happy to help test this if needed.

**Comment by paylakatel** [comment]
I took a [screen recording](https://drive.google.com/file/d/1csfx6Nx5gKgoj33TWE8ZW-SmmW40BNCt/view?usp=sharing) of me being able to reproduce this issue - not sure if it will be helpful. Maybe we add a delay of a second or two before transitioning from "Loading..." to "No address found"?

**Comment by mmcgowanBOS** [comment]
Hi Kayla,
I've tried to recreate this many times both locally and in Prod and have not be able to anymore. I did the exact same keystrokes and search as you did in your test (see screen recoding attached). This may have subsequently been fixed when we updated the cache settings for MNL to address the security issue with Google Translate a few weeks back. The fix was to exclude that JSONAPI endpoint from caching (see screenshot) which may have eliminated some stale results from previous searches.

Let me know if you are still that behavior. I'll be happy to look into it again, but this seems OK to me now.

Thanks.
https://drive.google.com/file/d/1WWmAz_Mi_3xaGRwkPPRDDKfisfBzglKs/view?usp=sharing

<img width="1282" alt="Screen Shot 2020-08-07 at 10 52 42 AM" src="https://user-images.githubusercontent.com/44584567/89660860-f03ab380-d89f-11ea-872d-cc7cb2c1985e.png">

**Comment by paylakatel** [comment]
Thanks for this - I'm also unable to reproduce it. I'll let you know if other users report the issue again.
