### ISSUE TITLE
RFP Issued Moment for Timeline

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1756]
QA NOTES:

- [x] Remove additional logic that forces RFP moment to display under "Selecting a Developer" stage (ok for it to show under Community Feedback stage). 
- [x]  Make the 'GO TO RFP LISTINGS' button all caps per Boston.gov design guidelines.
- [x] Remove the subcopy (spec change).
- [x] Change "open" to "opened" in the title - final should be 'Request for Proposals (RFP) Opened for Bidding'
- [x] Change 'LIST' to 'LISTINGS' in the button - final should be 'GO TO RFP LISTINGS'

See comment below for new UI screenshot (also updated in Figma)!

Technical spec =  If the Project field "RFP Issued Date" = TODAY or in the past then it should create an RFP Issued moment and link the user to DND's RFP page (https://www.boston.gov/departments/neighborhood-development/requests-proposals)

**Comment by lizcormack-bos** [comment]
Look forward to reviewing in design review tomorrow! 

My top two proposals are at the top, but feel free to take a look at the other options below. I want this to feel consistent with past community meetings in the timeline, but also stand out. Would love everyone's input on how "dominant" this should feel visually - I think it's an important moment, but not sure how distinct it should feel.

![RFP Issued Moment_Concepts.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/a8c235fa-6e75-4b25-82a3-a00e118dfaa7)

**Comment by AmyWipfler** [comment]
I have a preference for the shorter versions under All Concepts, mostly because their content works well both in a future voice and a past voice. Since we don't have data yet to know when these close, unlike community meetings, we cannot have a past voice moment on the timeline be different from a future voice moment.

**Comment by AmyWipfler** [comment]
@lizcormack-bos I've moved this over to In Development for a new sprint. Can you post the specs here for the design you want built? Thanks!

**Comment by lizcormack-bos** [comment]
Final spec -- "Go to RFPs" button should link to this page: https://www.boston.gov/departments/neighborhood-development/requests-proposals

This is triggered by the "RFP Issued Date" in Salesforce (which should be the date that displays on the timeline).

![RFP Issued.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/689028ba-d573-4ab3-9aae-05aa4ef36e14)

**Comment by AmyWipfler** [comment]
Looks great! And takes me right to the RFP list :)

On projects like this one ( https://d8-ci.boston.gov/bh/demo/project/highlandmarcella-package-4) where we have all the timeline dates, can we add a tech spec so that it positions itself in the timeline chronologically?

**Comment by lizcormack-bos** [comment]
Updated (final) UI --

![Screen Shot 2021-01-19 at 5.13.50 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/7ee2b314-1bca-4035-b0e1-8327191182af)

**Comment by lizcormack-bos** [comment]
Also assigning myself since I need to come up with a clever solution to address these scenarios (where the RFP was issued but the DO didn't update the project stage...)

![Screen Shot 2021-01-19 at 5.10.14 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/3a3224eb-c16d-44fd-bfe2-fcc9eb300cf2)

**Comment by lizcormack-bos** [comment]
It looks like we're forcing the RFP Issued moment to show up under "Selecting a Developer" even if the stage hasn't become active - I vaguely remember having that conversation, but want to remove that logic for now to avoid the scenario in the screenshot.

Note for the record: It looks like this happens pretty often. Amy I discussed today whether we should consider updating the stage logic so that "RFP in Progress" triggers "Selecting a Developer" instead of "Community Feedback" - let's discuss that further before we make any logic changes. For now, RFP moment should show up in whichever stage is active at the time.

![Screen Shot 2021-01-19 at 5.10.14 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/3a3224eb-c16d-44fd-bfe2-fcc9eb300cf2)
