### ISSUE TITLE
Legend for the Map

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1799]
Gentle lift map legend that focuses on explaining the icons on the map. Test placement and content with Maze testers before development.

**Comment by lizcormack-bos** [comment]
I have a few concepts for a legend, but would prefer to omit it if we can since it takes up a lot of real estate. 

Exploring the legend ideas and getting feedback from Sebastian led to some convos about turning the left sidebar into a floating panel that can be collapsed and expanded, which might also translate well to mobile. 

Here's the report from the Maze test I ran which did a pretty good job of validating that with the content preview cards working, the legend isn't needed to confidently identify project type: https://app.maze.design/report/7byjjgmqkkh1l4wc

Here's a user test clip of the user identifying icon meaning w/o a legend: https://grain.co/highlight/UZFdJbfJhXcb3rtvTBMff5vAUvGvSyrUtgvTfLSc

**Comment by AmyWipfler** [comment]
Thanks for the update! I'll move this out of your queue for now. So glad our tests went so well!

**Comment by lizcormack-bos** [comment]
This is a duplicate - see 1947 for map legend details: https://app.zenhub.com/workspaces/buildinghousing-product-board-5bdb03f74b5806bc2bf0117c/issues/cityofboston/boston.gov-d8/1947
