### ISSUE TITLE
UI updates for How-To page

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1808]
Currently, How-To pages use a tabs, located below the header, to differentiate between sections. UX research has demonstrated that users often miss these tabs as they scroll down the page. To address this issue, the tabs should be replaced by series of drawers, as shown in the wireframe below:

<img width="925" alt="Screen Shot 2021-01-14 at 9 18 22 AM" src="https://user-images.githubusercontent.com/57111927/104602492-762a0a00-5649-11eb-8b72-7deef46253ee.png">

The current UI is shown below for reference: 

<img width="1434" alt="Screen Shot 2021-01-14 at 9 19 02 AM" src="https://user-images.githubusercontent.com/57111927/104602597-8f32bb00-5649-11eb-8733-7c63c3dad109.png">

Complete specs can be found here: https://www.boston.gov/sites/default/files/embed/a/annotated_wireframes.pdf

The "carrot" indicating the state (open/closed) of the drawers has also been shown to be confusing for users, and should be replaced by a +/- symbol indicating open/closed state, respectively. The content of the new drawers is identical to the content previously housed in each tab.

**Comment by padora-cob** [comment]
Duplicates(?):
- https://github.com/CityOfBoston/creative-team-workflow/issues/1170
- https://github.com/CityOfBoston/boston.gov-d8/issues/320

**Comment by rachelsater** [comment]
Let me ask Reilly for her thoughts....

**Comment by rachelsater** [comment]
@padora-cob Nope, 1170 is for the creative team and 320 is for development. But it looks like https://github.com/CityOfBoston/boston.gov-d8/issues/320 and https://github.com/CityOfBoston/boston.gov-d8/issues/1808 are dupes. Should I close one and if yes, which one?

**Comment by padora-cob** [comment]
Let's keep this one (#1808), I have already made a new branch that I am working off of based on this ticket number.

**Comment by rachelsater** [comment]
perfect - thanks!

**Comment by duffy-james** [comment]
@padora-cob this is looking great and love these improvements. Couple of issues I'll flag here that I think we've already discussed.

1. We need to work out the styling on mobile. The end and the beginning of each step is a little too tight on top of each other:
![image](https://user-images.githubusercontent.com/7929556/114239192-c1576e80-9953-11eb-8ffd-87add7d88ab4.png)
![image](https://user-images.githubusercontent.com/7929556/114239214-c74d4f80-9953-11eb-823e-a3ca3985aa8c.png)

I think we need to add some padding and that should cover us. Adding a rule feels unnecessary. We also have to figure out what to do with the number when the screen is that small. I defer to @sebastianebarb on that.

2. The "show" / "hide" option is a great improvement. We should consider adding this to our "drawers" component on the site.

3. There's one minor addition I think we need to potentially make. There are a handful of how-to pages where there's just one "tab", typically when there's only an online application to complete something. Maybe in those situations where there's just one tab we default to having that one tab open? Otherwise, it might look a little silly with the extra white space in the middle.

**Comment by rachelsater** [comment]
thanks James! I'll put this one back in "In Progress"

**Comment by padora-cob** [comment]
Can test the single tab auto-open and mobile styles at: https://d8-ci.boston.gov/departments/neighborhood-development/boston-home-center/get-financial-help-remove-lead-your-home

**Comment by rsater-storycorps** [comment]
@padora-cob please move this to live when you have time

**Comment by duffy-james** [comment]
@padora-cob @rachelsater this is looking good to me. I just tested everything on CI. Only potential flags:

1. Ideally we'd tighten up the spacing here on mobile:
![image](https://user-images.githubusercontent.com/7929556/127182556-e9f3ecfb-f55f-453a-abee-bcba18387117.png)

2. I assume we landed on just centering the numbers here:
![image](https://user-images.githubusercontent.com/7929556/127182614-4324fd1c-1b0f-405e-a0ed-6dc82e0a9b61.png)

That makes sense to me, but just want to confirm Sebastian (or another designer) gets a chance to take a look. I don't think this should hold up pushing this live, though, just something to look at post launch.

3. Flagging this for myself, but I'll need to go through and revisit each how-to page on the website when this launches. Any pages with a lot of content in the sidebar will now have a lot of white space under the new drawers sections on desktop.
