### ISSUE TITLE
Changes to WYSIWIG

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#216]
Remove the following items from the WYSIWIG:

- [x] Both x2s
- [x] first copy and paste
- [x] styles view (next to source)

Change:
- [x] Having both 'normal' and 'styles' dropdown confuses people > convert to only one dropdown option and rethink the available fields. Keep the word styles
- [ ] Change the 'E' to an image as it matches current view in D7

Text format (at bottom): 
- [x] Only roles that can access full html are site admin and above. 
- [x] All lower roles get filtered html. 
- [x] Get rid of  the other two items in this list

**Comment by zweishar** [comment]
This all done, save for changing over the icon. I think this should wait until we have a database that we're not going to destroy/rebuild because the icon is stored on the public file system (not stored in git) and the configuration file stores a reference to the file's UUID, which will keep changing until we have a canonical database to work off.

When time comes, we can use the image icon that CKeditor uses, which is stored at: `docroot/core/modules/ckeditor/js/plugins/drupalimage/icons/drupalimage.png`
