### ISSUE TITLE
Permissions issue on JS file preventing users from opening "drawers" for filtering events and news pages

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2498]
We're receiving reports that users are unable to open up the "drawers" on our website for filtering on our [calendar listing page](https://www.boston.gov/events), [public notices site](https://www.boston.gov/public-notices), and [news page](https://www.boston.gov/news). When they click on the drawer to open up filtering options, nothing happens:

![image](https://user-images.githubusercontent.com/7929556/167888887-715139b8-69f1-4032-93a8-67436a2833fb.png)

This appears to be a permissions issue. Users are able to click and open the drawers on the City network, but users outside of the City network are unable to. @davidrkupton flagged that we're seeing a 403 error:

![image](https://user-images.githubusercontent.com/7929556/167888164-7b4f7ad8-b370-40ed-836e-cafeb242339f.png)

This is a high-priority ticket and should be addressed as soon as we can.

**Comment by davidrkupton** [comment]
![image](https://user-images.githubusercontent.com/4700050/168147022-a70e6f80-3c9c-49c3-ad32-fa8c2920ee68.png)

**Comment by davidrkupton** [comment]
Response when requesing the js file:
![image](https://user-images.githubusercontent.com/4700050/168150061-eec78084-c4f1-4428-9b42-ff5e846cd5c2.png)

**Comment by davidrkupton** [comment]
## Comment
The cause of this issue is unexplained.  I believe that when Drupal made the aggregated JS file the permissions for the file were set in a subtly different way to the other js files, and which is not apparent from the basic console commands.  This has never happened before to boston.gov or any Drupal site I have been involved with, so I'd say its a rare and probably not replicatable event.  The root cause may not even been Drupal, but rather a glitch on the AWS server itself while the file was created.

## Resolution
1. SSH onto production server
2. manually delete the problematic js file 
3. run drush cr and drush updb
4. flush the varnish cache for boston.gov and www.boston.gov domains
