### ISSUE TITLE
Find a module to allow the cloning of an entire node.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#264]

**Comment by jimafisk** [comment]
[Entity clone](https://www.drupal.org/project/entity_clone)?

**Comment by zweishar** [comment]
I have verified that this module is installed and working on the develop branch. I also configured defaults for this module so that it's more user-friendly. By default, the module prompts you to select which child entities to clone each time you want to clone something. I have set it up to no longer prompt and to create new entities for paragraphs + files only. All other child entity types will still reference the original entity.
