### ISSUE TITLE
Review the module uninstall methodology. 

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#267]
(do we need the code in hook_uninstall)?

**Comment by jimafisk** [comment]
This comes down to whether or not we want config to continue to live in the db after a module has been uninstalled. Since modules also enables the templates and preprocess, I would think that we would not still want the config without the module (e.g. without theming we would have field structure, etc in the database that can't be displayed). 

So I _think_ we're going to still want the `hook_uninstall` code, but I know there were some other thoughts on this issue, so I'd definitely be interested in hearing them.

I think one potential concern was that deleting config also deletes content. My thought is the modules will have to stay enabled anyways for reasons mentioned above, but I could see how this might make certain dev tasks more difficult.

**Comment by davidrkupton** [comment]
The modules only have field instance settings.  The `bos_components` module has the field.storage settings files.  So hook_uninstall will remove the field instances from the UI and DB, but not the data ...

**Comment by reillyzlab** [comment]
Done so closing
