### ISSUE TITLE
Media Migration

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#273]
The foundation for how we're handling media in D8 is details here: https://github.com/CityOfBoston/boston.gov-d8/issues/210

We will need to migrate File Entities to Media Entities: https://www.drupal.org/project/migrate_file_to_media

Transitioning to core media: https://www.drupal.org/docs/8/core/modules/media/faq-transition-from-media-entity-to-media-in-core

Also need to revisit file storage, possibly offloading to S3: https://www.drupal.org/project/s3fs

**Comment by zweishar** [comment]
I'm currently thinking that we should forgo migrating every file field into media fields. Now that I understand the requirements a bit better, I believe this is the ideal set up:
- Use media embeds in the WYSIWYG (as we're currently doing)
- Leave fixed fields (think hero image on a node) as standard file fields.

This seems ideal to me because:
- The media module seems like overkill for fixed file fields given our use case. Do content authors need the ability to re-use images accross different pages? For instance, will 2 pages share the same hero image? If not then we don't need the media module here.
- Not switching over fixed fields to media fields reduces the complexity of the migration
- Using media in the WYSIWYG (as we're currently already doing) gives us a lot more control over how content editors use files in the WYSIWYG, which is the primary way they upload files to the system. So I think we should leave this as it currently is.

Before making this decision, we should confirm the following with stakeholders:
- Content authors don't need to re-use media stored in fixed fields across different sections of the site.

Next Steps:
- Write managed file migration
- Write migration for WYSIWYG fields to use entity embed + media objects in place of hardcoded links to the public file system

**Comment by zweishar** [comment]
Next Steps:
- Write managed file migration
- Write migration for WYSIWYG fields to use entity embed + media objects in place of hardcoded links to the public file system

**Comment by zweishar** [comment]
Interesting note, we had an informational call with an external agency today that recommended not using media for fixed image fields (like we're recommending above) because it leads to complications in defining image styles correctly.

**Comment by zweishar** [comment]
File Migration Strategy:
- [ ] Rsync files to `/sites/default/files/migration`
- [ ] Create mangaged file entry for each file
- [ ] Set file storage as perminent
- [ ] Write process plugin for file fields that moves file from `/sites/default/files/migration` to directory `/sites/default/files/{YYYY-MM-DD}` (date last updated)
- [ ] Write process plugin for rich text fileds that performs the above action + switches `<img>` tag over to entity embed
- [ ] When migration is done and site is launched, delete all files in `/sites/default/files/migration` as they are not used anywhere.

Questions:
- Do we ever upload files to the public files directory that are used outside of Drupal? This could happen if we wanted to make a file publically available but don't explicitly reference it in Drupal. If we do this, then the above plan won't work as we have no way of knowing what we're breaking by cleaning up files.

**Comment by davidrkupton** [comment]
Thanks Zach.

**Comment by zweishar** [comment]
We currently have managed files of the following types:
```
.jpg
.jpeg
.png
.pdf
.svg
.gif
.xls
.xlsx
.docx
.doc
.tif
.pptx
.pptm
.ppt
.rtf
.mp4
.bin
.jnlp
.psd
.ppt
.xlsm
```

**Comment by zweishar** [comment]
```
mysql> select filemime from file_managed group by filemime;
+---------------------------------------------------------------------------+
| filemime                                                                  |
+---------------------------------------------------------------------------+
| application/msword                                                        |
| application/octet-stream                                                  |
| application/pdf                                                           |
| application/rtf                                                           |
| application/vnd.ms-excel                                                  |
| application/vnd.ms-excel.sheet.macroEnabled.12                            |
| application/vnd.ms-powerpoint                                             |
| application/vnd.ms-powerpoint.presentation.macroEnabled.12                |
| application/vnd.openxmlformats-officedocument.presentationml.presentation |
| application/vnd.openxmlformats-officedocument.spreadsheetml.sheet         |
| application/vnd.openxmlformats-officedocument.wordprocessingml.document   |
| application/x-java-jnlp-file                                              |
| image/gif                                                                 |
| image/jpeg                                                                |
| image/png                                                                 |
| image/svg+xml                                                             |
| image/tiff                                                                |
| image/x-photoshop                                                         |
| video/mp4                                                                 |
+---------------------------------------------------------------------------+

```
