### ISSUE TITLE
Media Testing

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#274]
We need to run QA on:
- Migrated Media
- Editor workflow

Need to automate checking for broken links.

**Comment by zweishar** [comment]
We can write a process plugin to search for broken links. I think the easiest way would be to use Guzzle (provided by Drupal) to make requests to each URL and check the status code. If a URL returns anything other than 200 we can log the relevant information (perhaps `entity_id`, `field_name`, `link value`, `status code`) so that we have a record to refer to afterwards. This process plugin should be run at the end of the process pipeline for each link / image / rich text field.

The main downside of this approach is that it will significantly slow down migration process as we will be making numerous http requests, which take time to return. Also, if we aren't careful we will make a significant number of requests to our production server, which could negatively impact the production application.

Another option is to use a site crawling too, like https://www.screamingfrog.co.uk/seo-spider/ during the Q/A process. This has the benefit of requiring no work to implement, but the downside of reduced specificity when errors are flagged (no entity_id).

**Comment by zweishar** [comment]
@davidrkupton @jimafisk do you have an opinion on this ^ ?

My preference is for screamingfrog because it's less work for us. If it turns out to be inadequate we can always add the process plugin down the line, but I generally like to start light and beef up if needed.

**Comment by davidrkupton** [comment]
It seems we already have a licence for `siteimprove` which also checks for broken links.  Not sure if we can use on our dev instances - or if its suitable, but its a tool already used....
I just cc'd an email to you both incase you dont have a reference...

**Comment by jimafisk** [comment]
I agree, using an external service to check links should be fine.

**Comment by zweishar** [comment]
I used the following command to rsync files from d7 dev to d8 dev:
```
rsync -nrltDvPh -e "ssh -i /mnt/gfs/bostond8dev/sites/default/files/private/private_key" boston.dev@staging-15139.prod.hosting.acquia.com:/mnt/gfs/bostondev/sites/default/files/ /mnt/gfs/bostond8dev/sites/default/files/ --exclude 'css' --exclude 'js' --exclude 'honeypot' --exclude 'styles' --exclude 'xmlsitemap' --exclude '*.bin' --exclude '*.jnlp' --exclude '*.psd'
```

I am going to remove my private key from the server after this is over. You will need to add your own private key if you wish to do this again
