### ISSUE TITLE
Add ability to choose theming for select components

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#322]
Allow [nearly] all components to change color theme between white, gray, or blue

Components that still need:
- [ ] Three column with image
- [ ] Cabinet
- [ ] Drawers
- [ ] Group of Links - Grid [w/ and w/o Description]
- [ ] Group of Links - Mini Grid
- [ ] Group of Links - List
- [ ] Group of Links - Quick Links
- [ ] Grid of Guides
- [ ] Grid of Quotes
- [ ] Formatted Text
- [ ] Transaction Grid
- [ ] Feedback (larger issues here)
- [ ] News/Announcements
- [ ] Upcoming events

**Comment by reillyzlab** [comment]
Dependent on design designating what each color layout looks like - corresponding ticket: https://github.com/CityOfBoston/boston.gov-d8/issues/322

**Comment by jimafisk** [comment]
Updating all components this way would likely exceed a week (largest sprint label).

**Comment by andrebtlima** [comment]
Need to determine which components currently can be themed, just to make sure the above checklist is still correct.

**Comment by padora-cob** [comment]
Components ready for review and feedback:
- [ ] Three column with image
- [ ] Cabinet
- [ ] Drawers
- [ ] Group of Links - Grid [w/ and w/o Description]
- [ ] Group of Links - Mini Grid
- [ ] Group of Links - List
- [ ] Group of Links - Quick Links
- [ ] Grid of Guides
- [ ] Grid of Quotes
- [ ] Formatted Text
- [ ] Transaction Grid
- [ ] Feedback (larger issues here)
- [ ] News/Announcements
- [ ] Upcoming events

**Comment by reillyzlab** [comment]
On gray background page, the following need the department contact fixed. This should be red with light blue hover to match the other components (example below):
- [ ] three column with image
- [ ] Grid of guides 

<img width="585" alt="Screen Shot 2021-05-11 at 10 48 11 AM" src="https://user-images.githubusercontent.com/20731897/117861548-652f8500-b246-11eb-9b6a-0f63b385de03.png">

**Comment by reillyzlab** [comment]
@padora-cob @sebastianebarb realize it wasn't originally on the ticket but is there a reason we didn't do the commissions components?

**Comment by padora-cob** [comment]
> @padora-cob @sebastianebarb realize it wasn't originally on the ticket but is there a reason we didn't do the commissions components?

I don't think so, I simply went off the list above. I think there could be a few more components we could add this to though. Would just want to add them to the list so I don't lose track with all the files flying around.

**Comment by duffy-james** [comment]
1. Aside from the issues @reillyzlab flagged, here are some others:

The "short description" field in the individual drawers appears to be a blue color that's blending into the background slightly:

![image](https://user-images.githubusercontent.com/7929556/118151593-c8095380-b3e1-11eb-9774-d81cd57a73ed.png)

It's a little different, but I imagine this would cause an accessibility issue.

2. The "short description" for the individual links in the "group of links - list" with and without description components is blending into the background. You can only see the text when you hover over the link with your mouse:

Normal:

![image](https://user-images.githubusercontent.com/7929556/118152888-3ac6fe80-b3e3-11eb-9c20-95121ebc3e57.png)

![image](https://user-images.githubusercontent.com/7929556/118152969-59c59080-b3e3-11eb-81bd-ca3a5b73b60f.png)

Hover state

![image](https://user-images.githubusercontent.com/7929556/118153001-64802580-b3e3-11eb-929c-e10bc1f38309.png)

![image](https://user-images.githubusercontent.com/7929556/118153054-7366d800-b3e3-11eb-8309-9b750c243c1a.png)

3. The "newsletter" component has extra white space at each corner of the component:

![image](https://user-images.githubusercontent.com/7929556/118153146-8c6f8900-b3e3-11eb-9512-8476b9ff6620.png)

4. This is related to the spacing issues in between components, but I'm still seeing extra white space and other issues. It might just be related to the "emergency alerts" component, as that is the common denominator.

There's extra white space in between this "maps" and "emergency alerts" component:

![image](https://user-images.githubusercontent.com/7929556/118153334-c771bc80-b3e3-11eb-8d06-128edf004662.png)

This is in between the "iframe" and the "emergency alerts" component:

![image](https://user-images.githubusercontent.com/7929556/118153441-e7a17b80-b3e3-11eb-84e5-61dfe7dc2fd4.png)

5. The "featured" event also appears to be missing text because it's blending into the background:

![image](https://user-images.githubusercontent.com/7929556/118153618-191a4700-b3e4-11eb-9fae-2374e5109b81.png)

If click and drag over that section, you can see the missing text:

![image](https://user-images.githubusercontent.com/7929556/118153713-30593480-b3e4-11eb-8b34-8c3bf9c2a8e2.png)

**Comment by duffy-james** [comment]
For the "white" themed components, here are some minor issues:

1. The "short description" text in the individual "drawers" of the "drawers" component blends into the background:

![image](https://user-images.githubusercontent.com/7929556/118155554-55e73d80-b3e6-11eb-90a3-2ae206ae5672.png)

2. There's extra spacing in between the "FYI" component and a "photo" component:

![image](https://user-images.githubusercontent.com/7929556/118156219-1a993e80-b3e7-11eb-9a48-00108e9d138a.png)

**Comment by duffy-james** [comment]
There are also some minor issues with the "gray" components:

1. There's extra spacing in between a few components (probably a separate issue, but just a flag):

"Drawers" and "quick links" components:

![image](https://user-images.githubusercontent.com/7929556/118158838-4b2ea780-b3ea-11eb-8b76-5e7fbf132766.png)

"Group of links - list" and "photo" components:

![image](https://user-images.githubusercontent.com/7929556/118158986-7b764600-b3ea-11eb-9044-60b3dd2d141f.png)

"Grid of cards" and "photo" components:

![image](https://user-images.githubusercontent.com/7929556/118159073-95178d80-b3ea-11eb-899d-b33b5078803f.png)

"FYI" and "photo" components:

![image](https://user-images.githubusercontent.com/7929556/118159177-b5474c80-b3ea-11eb-83ca-ed0871262ebb.png)

"Formatted text" and "photo" components:

![image](https://user-images.githubusercontent.com/7929556/118159251-cabc7680-b3ea-11eb-898e-5849df597faf.png)

"Map" and "emergency alerts" components:

![image](https://user-images.githubusercontent.com/7929556/118159489-0f481200-b3eb-11eb-8d99-3f539a3da77e.png)

And it's tight in between the "emergency alert" and "iframe" components:

![image](https://user-images.githubusercontent.com/7929556/118159578-2be44a00-b3eb-11eb-9405-0b5775ce24cb.png)

2. The "newsletter" component also has four white corners:

![image](https://user-images.githubusercontent.com/7929556/118159864-91383b00-b3eb-11eb-8a5b-8077e53783f4.png)

**Comment by stephaniemar** [comment]
Estimated about  1 weeks worth of work for this.

**Comment by duffy-james** [comment]
Closing this ticket; work is now being accounted for in Jira.
