### ISSUE TITLE
Downtown Parking Freeze Article: Multiple contact prompts

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#517]
Under the right column, there are multiple contact prompts (i.e. "Still have questions? Contact:" Have questions? Contact us:")

D7: https://www.boston.gov/departments/environment/air-pollution-control-commission/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655285-a5eec180-b92f-11e9-81ff-4e1834e119f1.png)

D8: http://bostond8dev.prod.acquia-sites.com/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655282-a38c6780-b92f-11e9-9f5a-2c9349ed95fa.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Related to #601

**Comment by andrebtlima** [comment]
Original issue here is fixed but there's a still a spacing issue. Not a launch blocker I don't think, fixable after launch, article hasn't been updated since Jan 2018 too. 

After the _Have questions? Contact us_ prompt, there's an extra paragraph in the D8 version: 

<img width="1304" alt="Screen Shot 2019-11-05 at 10 57 51 AM" src="https://user-images.githubusercontent.com/57111927/68223743-574ad500-ffbb-11e9-979e-3219efcb1ee5.png">

And in the the D7 version:

<img width="1313" alt="Screen Shot 2019-11-05 at 10 58 40 AM" src="https://user-images.githubusercontent.com/57111927/68223771-6467c400-ffbb-11e9-90d8-8df5a46059a8.png">

**Comment by andrebtlima** [comment]
Remaining issue was already raised in ticket #601, so closing this ticket.
