### ISSUE TITLE
message_for_the_day

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#61]
depends on:
- document
- external link
- internal link

**Comment by zweishar** [comment]
**Notes**
- These need to be edited and updated a lot
- The current system is complicated because there was a requirement to show street cleaning notices (ex. 1st wed of the month)
- It's not possible to preview what these will be currently, so James has to guess and hope that it works out on the day of.

**Questions**
- Do people even come to boston.gov for that type of information?
- Is the engineering effort (tbd) worth it for the number of people this message serves (why can't people figure out what day of the month it is on their own?)

**Enhancements**
- Create page for content authors to preview what the status items will look like on a given day.
    - Create a page that only admins can see
    - Add a calendar to the top of the page
    - Once a date is selected on the calendar, render the status items view as it would appear on that day

**Comment by zweishar** [comment]
@reillyzlab I'd like to flag ^ as something to discuss in our meeting on Thursday.

**Comment by zweishar** [comment]
I'm going to assign this to Reilly + James as we have some outstanding project management / strategy issues to nail down before we move forward.

**Comment by zweishar** [comment]
After talking, it's unclear if we can remove the messages we put up for street cleaning. I'm going to push forward on this and try to make a system that is as simple as possible given the requirements above.

**Comment by zweishar** [comment]
**Options Currently Available**

- Start Date
    - Single date field
- Frequency:
    - Once
    - Daily
        - Repeat every X days (enter a number)
        - Every weekday
        - Every Mon, Wed, Fri
        - Every Tue, Thu
    - Weekly
        - Every X weeks (enter a number)
        - Day of week (multiple select boxes)
    - Monthly
        - On X day of (1 - 31)
        - Month of year (multiple select boxes)
        - On Xth Day of week (4th thursday of month)
        - Month of year (multiple select boxes)
    - Yearly
        - Repeat every X years
        - (identical options to Monthly)

Stop repeating:
  - After X number of occurances
  - On Date

Exclude Days:
  - Date field (unlimited cardinality)

**Comment by zweishar** [comment]
Current structure:

Node -> List Component -> Homepage Status details (view) -> Status Item (node) -> Message of the Day (paragraph)

Only published Status Item nodes are displayed (makes it easy turn on / off)
Status item nodes have multiple message of the Day's attached, each with different date recurrences. Message of the day is displayed based on configured recurrence.

Status Item node has an icon field that is used for every attached paragraph. Each paragraph has the option not use the default icon.
