### ISSUE TITLE
Thumbnail Images not showing on news_and_events views.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#627]
Maybe related to #452 .

**Comment by reillyzlab** [comment]
@jimafisk checking on what this view powers

Is it just the new_and_events view populate the news and events components or just boston.gov/news and boston.gov/events?

**Comment by reillyzlab** [comment]
Still some sort of an issue going on:
![Screen Shot 2019-09-25 at 2 14 04 PM](https://user-images.githubusercontent.com/20731897/65628105-c980d080-df9e-11e9-86cf-c47d60fb3b41.png)

**Comment by jimafisk** [comment]
Both news and events pages are powered by the `list` component. 

News:
- URL: https://www.boston.gov/news
- View: `bos_news_landing`
- View Display: Page

Events:
- URL: https://www.boston.gov/events
- View: `calendar`
- View Display: Listing

I don't see a `new_and_events` View, are you referring to `/admin/structure/views/view/news_and_announcements/edit`?

**Comment by reillyzlab** [comment]
May not be a launch blocker but wanted to keep launch blocker for now to check whether it's a larger media issue or not

**Comment by jimafisk** [comment]
Sorry I must have missed your screenshot, looks like you are referring to the `news_and_announcements` and `events_and_notices` components. Can you add the link for that specific page? 

`news_and_announcements` only displays content of type `post`.

`events_and_notices` displays content of type `event` and `public_notice`.

**Comment by reillyzlab** [comment]
Found on homepage: http://bostond8stg.prod.acquia-sites.com/ [scroll down to news/announcements]

**Comment by jimafisk** [comment]
Ah, thanks! That's weird super weird that some work and some don't considering they are all posts. 

I noticed the wrapping element is referencing a local url, so that should be removed:
```
.news-item-short-listing .thumb-wrapper.float-left {
    background-image: url(https://boston.lndo.site/modules/custom/bos_content/modules/node_post/default_news.svg);
}
```

The sub element references the actual img:
```
.news-item-news .news-item-default-image, .news-item-post .news-item-default-image {
    background-image: url(../images/public/icons/news.svg);
}
```

The last item in the list is not getting the `<div class="news-item-default-image">` markup added to it, so we'll need to update the template.

**Comment by jimafisk** [comment]
So what appears to be happening here is that the template checks if a thumbnail exists, and if it doesn't it displays the default image. In this particular case the news item that is missing the image (`/news/mayor-signs-home-rule-petition-strengthen-ability-create-affordable-housing-fund-workforce`) actually does have a thumbnail, but it appears to be broken.

<details>
<summary>What it looks like in D7</summary>

![working_thumb](https://user-images.githubusercontent.com/5913244/65718719-200b0f00-e072-11e9-9430-5073dce57e42.png)

</details>
<details>
<summary>What it looks like in D8</summary>

![thumb](https://user-images.githubusercontent.com/5913244/65718723-24cfc300-e072-11e9-9235-48ec7d9efb1c.png)

</details>

cc'ing @davidrkupton since he is working on media. I'll push a fix that removes the local URL from the style.

**Comment by andrebtlima** [comment]
Image is coming through but theres a size issue:

<img width="1429" alt="Screen Shot 2019-11-04 at 3 40 31 PM" src="https://user-images.githubusercontent.com/57111927/68156292-890b5f80-ff19-11e9-9106-64a0833be3f0.png">

**Comment by andrebtlima** [comment]
Resolved so closing.
