### ISSUE TITLE
recollect_widget

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#68]

**Comment by zweishar** [comment]
I connected with James on this and we're not using this component on D7. There is one place we use the recollect service, but it's done as a script embed.

No need to port this component if it's not in use.

**Comment by jimafisk** [comment]
Working on the `script_page` now. It looks like `field_embed_list` actually references this component in order for the script embedding to work.

**Comment by jimafisk** [comment]
Upon further investigation, there is only one record in the database for this paragraph and it's archived:

| item_id | revision_id | bundle | field_name | archived |
|-----------|----------------|-----------|----------------|---------|
| 105256  | 1651106 | recollect_widget | field_embed_list | 1 |       

Since there are no recollect widgets currently public on boston.gov I think it's fine to keep with the original proposal to close this.
