### ISSUE TITLE
script_embed

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#69]

**Comment by zweishar** [comment]
This component is currently used on one page: https://www.boston.gov/news/mayor-walshs-speech-greater-boston-chamber-commerce

This page is a news item from 2016.

The component is used to embed an annotation tool called Genius. Since we're only using this component in one place, and the page is so old, I'd recommend that we decommission this component. So that we don't need to worry about it in the migration.

@reillyzlab @duffy-james, do either of you have an opinion on this? I'm happy to keep it for D8 if we want, but I'm also trying to clean up un-used cruft along the way.

**Comment by zweishar** [comment]
I spoke with Reily and we agreed that we don't need to migrate this. She brought a good point that we should re-visit the way that we embed scripts in Drupal, but we can do that at our next meeting. Either way it would be an update to the way we do things moving forward, not a migration task.
