### ISSUE TITLE
user_action

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#83]
depends on:
- external link
- internal link
- document

**Comment by jimafisk** [comment]
It does not appear this paragraph is actually being used anywhere on the site. If you check the `paragraphs_item` table and search for this bundle, there are no records. 

Per @duffy-james "I don't recall using it"

Here is a screenshot of what it looks like on my local D7 setup:

![user_action](https://user-images.githubusercontent.com/5913244/51043703-5446aa00-158d-11e9-8d2e-78bac0de7ad0.png)

I'm closing this since I think we should decommission and not port it over to D8. If someone has evidence to the contrary, please reopen. Thanks!
