### ISSUE TITLE
Issue with event date format - won't allow event to save

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#846]
A user can enter the event date in the desired way, but when they try to save it the event will not save because it is not matching the accepted formatting for Drupal.

![Screen Shot 2019-11-12 at 4 13 05 PM](https://user-images.githubusercontent.com/20731897/68711332-6a374980-0567-11ea-9112-d2247bf12db6.png)

**Comment by andrebtlima** [comment]
Trying to enter a start date and time for the event. The time field only allows me to put in AM or PM not seconds (i.e. 00:00 AM/PM) but when I try to save the changes it throws me this error, saying I need to input the time in 00:00:00 format. 

<img width="1419" alt="Screen Shot 2019-11-15 at 11 41 48 AM" src="https://user-images.githubusercontent.com/57111927/68959996-3e9da480-079d-11ea-8494-0ac58053681d.png">

**Comment by jimafisk** [comment]
This is still happening with the new `field_event_date_recur` on Events, submitting the form empties the field and flags it as required:

![saving_dates](https://user-images.githubusercontent.com/5913244/69098074-d9101900-0a25-11ea-9a80-ad7d1294b229.png)

@andrebtlima is right that it wants a date in the format `00:00:00` but the widget provided forces `00:00 AM`.

**Comment by jimafisk** [comment]
The issue is that there's a `type` attribute on the `input` being set to `time`. We can override this in bos_core: https://www.drupal.org/project/webform/issues/2990482#comment-12861448

**Comment by jimafisk** [comment]
I was wrong previously, turns out the validation failure happens if you do not set a "timezone" value:

![timezone](https://user-images.githubusercontent.com/5913244/69164505-1fb15200-0abe-11ea-87df-70191d3587dd.png)

The node will save successfully using the date picker widget if this value is set.

It's probably best to use a different form display widget that is more intuitive out of the box. Here's an example of one called `Modular: Alpha`:

![alpha](https://user-images.githubusercontent.com/5913244/69164879-bf6ee000-0abe-11ea-83f8-4c5e56de5aef.png)

@duffy-james this widget seems much more intuitive, but it'd be great to test with you to confirm.

**Comment by reillyzlab** [comment]
Resolved
