### ISSUE TITLE
Issue with published/change to state on already published content (all content types)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#848]
On any content type, if a page is published and an admin goes to the green 'published - live' drop down in the upper right hand corner and selects the orange 'edit content' button then the page that opens up shows 'current state' published with the 'change to' state set to published.

This 'change to' state should be defaulting to 'draft' not 'published'.

True for admins and content editors.

Examples:

- ![Screen Shot 2019-11-12 at 4 33 59 PM](https://user-images.githubusercontent.com/20731897/68712694-41fd1a00-056a-11ea-9817-6d06610ff202.png)

![Screen Shot 2019-11-12 at 4 46 27 PM](https://user-images.githubusercontent.com/20731897/68713738-84bff180-056c-11ea-89cf-c2bd6132c255.png)

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine I know the UI has changed but  I think the behavior remains. Is this something we want to address? thanks

**Comment by duffy-james** [comment]
@rachelsater this one is interesting — I don't even notice it at this point. I think this might be one we can close out. The onus is on us to more conscious of what the moderation state is when we're making changes, but since content authors only have the option to save a "Draft", it isn't really a system issue.

@Micah-Levine what do you think about this one? Has this messed you up a lot in editing the site?

**Comment by Micah-Levine** [comment]
@duffy-james This one doesn't bother me at all, I think it's fine to close this one out. @rachelsater
