### ISSUE TITLE
Inconsistency in the upcoming events component on homepage

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#960]
On the live site, I'm seeing the same event repeated in the featured spot and twice below that:
![image](https://user-images.githubusercontent.com/7929556/69506438-ade16a00-0efc-11ea-83d2-54904b6586ca.png)

This is how it appears on content.boston.gov, which looks correct:
![image](https://user-images.githubusercontent.com/7929556/69506494-e6814380-0efc-11ea-863c-e86bbc9b53f6.png)

Aside from the "featured" item [missing the date](https://github.com/CityOfBoston/boston.gov-d8/issues/903), there are also no public notices listed in the component.

**Comment by reillyzlab** [comment]
@davidrkupton potentially a cache thing

**Comment by mmcgowanBOS** [comment]
David and I spent some time this morning looking at the "Events and Notices" View and the "Upcoming" display for it. We couldn't figure out exactly why anonymous users are seeing the repeated content and authenticated users are seeing the proper display as expected.

We tinkered with the "Relationships" in the Advanced part of the display (on our local env) and were able to correctly view the display for both anon and authenticated users by removing the "require the relationship" section.

I don't know enough about the content and the View and all it's relationships to confidently make any permanent changes. I'm thinking Jim could pick this up from here and likely make the correct updates faster than us. 

I"m going to assign to Jim, but let me know if there are any questions, etc.

**Comment by reillyzlab** [comment]
Related to #895

**Comment by reillyzlab** [comment]
Related: #926

**Comment by jimafisk** [comment]
What you were trying was correct @mmcgowanBOS, those relationships used to be setup to remove an item from the list if it is placed as the Featured Item. Unfortunately, on D7 if an event was featured in any component, it was removed from all components. Since that was a bug, for the D8 launch we completely removed this logic (currently items will still appear in lists even if they are also featured). We can circle back on that functionality later, for now the two bugs flagged here should be all set.

<details>
<summary>Featured item date fix</summary>

![featured](https://user-images.githubusercontent.com/5913244/69989072-db3ba280-1510-11ea-9eff-83c82269120e.png)


</details>
<details>
<summary>Duplicate Events</summary>

Before:

![before](https://user-images.githubusercontent.com/5913244/69989182-15a53f80-1511-11ea-9d6c-61532b7305b4.png)

After:

![after](https://user-images.githubusercontent.com/5913244/69989202-1d64e400-1511-11ea-8fe4-f34b504ad558.png)


</details>

**Comment by reillyzlab** [comment]
@duffy-james can you check to see if this is resolved. I'm going to open a separate issue for the view portion.

Comment and reassign to me when you've checked.

**Comment by duffy-james** [comment]
I'm seeing updated events, but the "featured" flag is a blue background, not a white one:
![image](https://user-images.githubusercontent.com/7929556/70070300-5fe5f980-15c1-11ea-81bf-be7319ce5d58.png)

I don't remember if that's how it was before. It looks like we're using just the white background in the news component:
![image](https://user-images.githubusercontent.com/7929556/70070372-7c823180-15c1-11ea-93e2-1d071ec633e0.png)

**Comment by duffy-james** [comment]
Confirming that we did use the blue flag for the "featured" item in the "events & notices" component.

**Comment by reillyzlab** [comment]
Fixed
