### ISSUE TITLE
Issues with short urls

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#961]
Can't get boston.gov/trash to redirect to the trash and recycling guide. Instead, it redirects here:

https://www.boston.gov/node/32846

That throws a 404 error. When I try to filter and find the short url in the Drupal configuration, I get an error message that says "temporarily unavailable".

I'll drop other short urls with a similar error in this ticket if I come across them.

**Comment by reillyzlab** [comment]
@jimafisk similar to the metrolist link forwarding?

**Comment by jimafisk** [comment]
If you take a look at https://content.boston.gov/node/1321/edit it's an Article node for our 404 page.

I think we're getting the "Temporarily Unavailable" error when searching for a "trash" redirect (https://content.boston.gov/admin/config/search/redirect?redirect_source__path=trash&redirect_redirect__uri=&status_code=All&language=All) because it's referencing a page that doesn't exist.

@duffy-james to be clear, we want `/trash` to go to boston.gov/trash-and-recycling correct?

**Comment by jimafisk** [comment]
You can see one of the `/trash` redirects here: https://content.boston.gov/admin/config/search/redirect?redirect_source__path=tra&redirect_redirect__uri=&status_code=All&language=All&page=1

![trash](https://user-images.githubusercontent.com/5913244/69509886-ab850d00-0f08-11ea-9d09-00ce5bf352ec.png)
