### ISSUE TITLE
Headers reacting as links

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/boston.gov-d8#969]
The headers in the Brand guidelines now how a roll overstate. It acts as a link when it is not. 
from
![Screen Shot 2019-11-25 at 9 49 57 AM](https://user-images.githubusercontent.com/20642299/69550524-23831f80-0f69-11ea-853e-f01b945b7c89.png)
to
![Screen Shot 2019-11-25 at 9 50 03 AM](https://user-images.githubusercontent.com/20642299/69550527-24b44c80-0f69-11ea-817c-725d14bf3149.png)

**Comment by reillyzlab** [comment]
The only that appears to have this issue is 'primary colors'. 

Tried to get into the 'formatted text' component 'color' to see if I could take care of this but I can't edit that component.

Tried on safari and firefox.

Page: https://content.boston.gov/departments/innovation-and-technology/brand-guidelines

**Comment by reillyzlab** [comment]
Fixed - removed words and retyped them.
