### ISSUE TITLE
'Auto' option not working on iframe component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#985]
When a user selects "auto" in the iframe component, it should set up an auto height for the iframed content. Right now, it's just showing a truncated version of the form:

![image](https://user-images.githubusercontent.com/7929556/69570930-e16cd480-0f8e-11ea-92bf-278da19b5d32.png)

**Comment by duffy-james** [comment]
@davidrkupton DND mentioned that Gary was using this file to get the forms to auto adjust:

https://www.boston.gov/sites/all/themes/custom/boston_public/dist/js/resizer.client.js

**Comment by subaha-cob** [comment]
@duffy-james I need more info on what you need done here. Did you want to change the height yourself or set a default height?

**Comment by subaha-cob** [comment]
@andrebtlima please test on UAT. You need to create an iframe to test each sizing option to make sure they are all still work.
https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@subaha-cob I still think this is broken, unless I'm misunderstanding something. Made a test article page in UAT with an iFrame component. Looks like it still pulling through a truncated version of the source page:

https://d8-uat.boston.gov/departments/digital-team/iframe-test

**Comment by subaha-cob** [comment]
@andrebtlima to be clear, for this to work as it use to, the iframe content must be on the same domain. What that means is that the content must be on boston.gov as well. Browsers will not allow you to do auto Iframe on another domain due to cross browser security issues.

Also I forgot to mention that to connect it, remove the https://boston.gov part, just add it relative. For example: 
Instead of: https://www.boston.gov/departments/neighborhood-development/metrolist/metrolist-listing-form
Use: /departments/neighborhood-development/metrolist/metrolist-listing-form

**Comment by andrebtlima** [comment]
@subaha-cob aaaah ok it was the second part, working now

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.

**Comment by subaha-cob** [comment]
Introduced a new issue. See ticket  https://github.com/CityOfBoston/boston.gov-d8/issues/1641

Need to go back and tighten code or find an alternative.

**Comment by subaha-cob** [comment]
![image](https://user-images.githubusercontent.com/57374913/97043991-57800f80-1541-11eb-8f7c-51b3ff2c97ea.png)

**Comment by reillyzlab** [comment]
Per Stella, this was resolved so closing this ticket.
